services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - 3000:3000"   
    environment:
      DB_HOST: db             
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSL: true
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      SUPERADMIN_NAME: ${SUPERADMIN_NAME}
      SUPERADMIN_EMAIL: ${SUPERADMIN_EMAIL}
      SUPERADMIN_PROVIDERACCID: ${SUPERADMIN_PROVIDERACCID}
      SUPERADMIN_PASSWORD: ${SUPERADMIN_PASSWORD}
      SUPERADMIN_CONFIRMPASSWORD: ${SUPERADMIN_CONFIRMPASSWORD}
      SUPERADMIN_PROFILEPICTURE: https://th.bing.com/th/id/OIP.audMX4ZGbvT2_GJTx2c4GgHaHw?rs=1&pid=ImgDetMain
      APP_PORT: ${APP_PORT}
    depends_on:
      - db  

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - "5432:5432"  

volumes:
  postgres_data: {}  