services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "${APP_PORT}:3003"   
    environment:
      DB_HOST: db             
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: pf_ft52
      DB_SSL: true
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      SUPERADMIN_NAME: superadmin
      SUPERADMIN_EMAIL: superadmin@gmail.com
      SUPERADMIN_PROVIDERACCID: 102036134540783805678
      SUPERADMIN_PASSWORD: "@IsStrongPassword1"
      SUPERADMIN_CONFIRMPASSWORD: "@IsStrongPassword1"
      SUPERADMIN_PROFILEPICTURE: "https://th.bing.com/th/id/OIP.audMX4ZGbvT2_GJTx2c4GgHaHw?rs=1&pid=ImgDetMain"
      APP_PORT: 3003
    depends_on:
      - db  

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - "5432:5432"  

volumes:
  postgres_data: {}  